name: "PR Title Check"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          scopes: |
            api
            web
            e2e
            deps
            chore
            docs
            infra
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            Tento projekt vynucuje Conventional Commits pravidla pro jména Pull Requestů.
            Zároveň nesmí popisek (subject) začínat velkým písmenem. 
            Například: 'feat: add timetable' místo 'feat: Add timetable'.
